name:          The Yellow Brick Road
description:   Follow, follow, follow, follow, follow the Yellow Brick Road.
url:           http://rtraction.github.io/yellow-brick-road

markdown:      rdiscount
permalink:     pretty
pygments:      true
